### ISSUE TITLE
Kwin crashes with segmentation fault (11) error when notification received from firefox

### ISSUE THREAD

**Issue by Mofiqul** [esjeon/krohnkite#65] opened 2020-03-19 11:57 UTC
Kwin freezes and crashes segmentation fault (11)  when notification received from firefox.

KDE Plasma Version: 5.18.3
KDE Frameworks Version: 5.67.0
Qt Version: 5.12.4
OS: Kubuntu 19.10

Firefox Version: 74.0

**Comment by esjeon** [comment] 2020-03-20 00:04
I've just tried to reproduce this on Kubuntu 19.10 on QEMU, and used [this](https://www.bennish.net/web-notifications.html) to send notifications from Firefox, but no success. Tried both vanilla and backport. Any more information?

Also, this can be an upstream or temporary issue, because notification windows are marked "special" by KWin, and Krohnkite ignores such windows.

**Comment by Mofiqul** [comment] 2020-03-20 06:27
Yes, I got this same problem with my two machines. Last night it crashed again when I stated Falkon. And I can not find any logs of segfault.

**Comment by esjeon** [comment] 2020-03-20 14:48
Hmm, I need more details about your setup. Multihead can be buggy due to bugs in kscreen. Graphics drivers can cause bugs, though rarely. I just wonder if your setup is simply a single laptop or a desktop w/ single screen.

Also, debug logs from Krohnkite and KWin can be really helpful. You can enable debug log in Krohnkite option, and restart KWin on terminal using `kwin_x11 --replace` to see the actual output.

**Comment by Mofiqul** [comment] 2020-04-06 18:38
Last whole week I have been using my laptop without Krohnkite and there was no kwin crash, not even a single time. From yesterday I again started using Krohnkite and kwin crash happened again. The crash occurred while opening a new tab in firefox.

## Here is log 

```
qml: [2704.703] arrangeScreen: layout=TileLayout(nmaster=1, ratio=0.5356463595839525) srf=KWinSurface(0, Default, 5) visibles=2
qml: [2704.704] KWinWindow#commit: geometry=Rect(10, 10, 715, 714) noBorder=false keepAbove=false
qml: [2704.706] KWinWindow#commit: geometry=Rect(735, 10, 621, 714) noBorder=false keepAbove=false
qml: [2704.706] arrangeScreen/finished: srf=KWinSurface(0, Default, 5)
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 62528, resource id: 54595802, major code: 2 (ChangeWindowAttributes), minor code: 0
qml: [2708.977] onCurrentSurfaceChanged: srf=KWinSurface(0, Default, 1)
qml: [2708.977] arrange
qml: [2708.977] arrangeScreen: layout=TileLayout(nmaster=1, ratio=0.55) srf=KWinSurface(0, Default, 1) visibles=1
qml: [2708.978] KWinWindow#commit: geometry=Rect(10, 10, 1346, 714) noBorder=false keepAbove=false
qml: [2708.978] arrangeScreen/finished: srf=KWinSurface(0, Default, 1)
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 65508, resource id: 54596700, major code: 2 (ChangeWindowAttributes), minor code: 0
OpenGL vendor string:                   NVIDIA Corporation
OpenGL renderer string:                 GeForce 410M/PCIe/SSE2
OpenGL version string:                  3.1.0 NVIDIA 390.129
OpenGL shading language version string: 1.40 NVIDIA via Cg compiler
Driver:                                 NVIDIA
Driver version:                         390.129
GPU class:                              GF100
OpenGL version:                         3.1
GLSL version:                           1.40
X server version:                       1.20.5
Linux kernel version:                   5.3
Requires strict binding:                no
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
kwin_scene_opengl: OpenGL 2 compositing setup failed
kwin_scene_opengl: OpenGL driver recommends XRender based compositing. Falling back to XRender.
kwin_scene_opengl: To overwrite the detection use the environment variable KWIN_COMPOSE
kwin_scene_opengl: For more information see https://community.kde.org/KWin/Environment_Variables#KWIN_COMPOSE
Application::crashHandler() called with signal 11; recent crashes: 1
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = kwin_x11 path = /usr/bin pid = 22717
KCrash: Arguments: /usr/bin/kwin_x11 --replace 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
[1]  + 22717 suspended (signal)  kwin --replace
```
### Below log message after the crash
```
qml: ["firefox","konsole","mpv","vlc","gwenview","gimp-2.10"]
qml: KROHNKITE: starting the script
qml: [0.588] Config: Config({
  "layouts": [
    {
      "classID": "TileLayout",
      "numMaster": 1,
      "masterRatio": 0.55,
      "weights": {
        "map": {}
      }
    },
    {
      "description": "Monocle",
      "classID": "MonocleLayout"
    },
    {
      "classID": "ThreeColumnLayout",
      "masterRatio": 0.6,
      "masterSize": 1,
      "weights": {
        "map": {}
      }
    },
    {
      "classID": "SpreadLayout",
      "description": "Spread",
      "space": 0.07
    },
    {
      "classID": "StairLayout",
      "description": "Stair",
      "space": 24
    },
    {
      "classID": "QuarterLayout",
      "description": "Quarter",
      "lhsplit": 0.5,
      "rhsplit": 0.5,
      "vsplit": 0.5
    },
    {
      "classID": "FloatingLayout ",
      "description": "Floating"
    }
  ],
  "maximizeSoleTile": false,
  "monocleMaximize": false,
  "monocleMinimizeRest": false,
  "adjustLayout": true,
  "adjustLayoutLive": true,
  "keepFloatAbove": true,
  "noTileBorder": false,
  "limitTileWidthRatio": 0,
  "screenGapBottom": 10,
  "screenGapLeft": 10,
  "screenGapRight": 10,
  "screenGapTop": 10,
  "tileLayoutGap": 10,
  "directionalKeyMode": "dwm",
  "layoutPerActivity": false,
  "layoutPerDesktop": true,
  "floatUtility": true,
  "preventMinimize": false,
  "preventProtrusion": true,
  "pollMouseXdotool": false,
  "floatingClass": [],
  "floatingTitle": [],
  "ignoreActivity": [],
  "ignoreClass": [
    "krunner",
    "yakuake",
    "spectacle",
    "kded5"
  ],
  "ignoreRole": [
    "quake"
  ],
  "ignoreScreen": [],
  "ignoreTitle": []
})
qml: [0.624] arrange
qml: [0.625] arrangeScreen: layout=TileLayout(nmaster=1, ratio=0.55) srf=KWinSurface(0, Default, 1) visibles=1
qml: [0.626] KWinWindow#commit: geometry=Rect(10, 10, 1346, 714) noBorder=false keepAbove=false
qml: [0.626] arrangeScreen/finished: srf=KWinSurface(0, Default, 1)
kwin_core: Compositing is not possible
trying to show an empty dialog
trying to show an empty dialog
trying to show an empty dialog
qml: [12.434] onCurrentSurfaceChanged: srf=KWinSurface(0, Default, 3)
qml: [12.435] arrange
qml: [12.435] arrangeScreen: layout=TileLayout(nmaster=1, ratio=0.55) srf=KWinSurface(0, Default, 3) visibles=1
qml: [12.435] KWinWindow#commit: geometry=Rect(10, 10, 1346, 714) noBorder=false keepAbove=false
qml: [12.436] arrangeScreen/finished: srf=KWinSurface(0, Default, 3)
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3733, resource id: 142606425, major code: 2 (ChangeWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4128, resource id: 144703494, major code: 18 (ChangeProperty), minor code: 0
QSocketNotifier: Invalid socket 10 with type Read, disabling...
QSocketNotifier: Invalid socket 8 with type Read, disabling...
Freeze in OpenGL initialization detected
Unable to start Dr. Konqi
Re-raising signal for core dump handling.

[1]  + 22717 abort (core dumped)  kwin --replace
```

**Comment by esjeon** [comment] 2020-04-11 04:56
If the crash happened while opening a new tab, it's unlikely that Krohnkite itself is buggy. The log clearly says that the last thing the script did is to arrange windows after switching desktop. It's more like this is a lower level(hardware or KWin) bug triggered by the script. I cannot guarantee if I can fix this.

Also, just in case, you can try [this version](https://github.com/esjeon/krohnkite/files/4464046/krohnkite-dev-slow.kwinscript.gz). I intentionally put 50ms delay to every window arrangement to avoid any collisions w/ KWin animations and any possible race conditions. You can install this w/:

        gunzip krohnkite-dev-slow.kwinscript.gz
        plasmapkg2 -t kwinscript -u krohnkite-dev-slow.kwinscript`.

Btw, have you tried other tiling scripts? Do they have the same problems?

**Comment by Mofiqul** [comment] 2020-04-18 11:49
No.. I didn't try any other tiling scripts. Looks like this is a issue with my hardware. The crash happen when the system under heavy CPU load.

**Comment by esjeon** [comment] 2020-04-18 23:52
That's quite interesting. Krohnkite may have actually topped off the safe limit there. It's a large chunk of Javascript code, so it may cause a burst of CPU usage for a very short period of time.

I think you might have a better luck with other scripts, or maybe you can switch to integrated GPU, if you have one.

**Comment by esjeon** [comment] 2020-05-31 17:47
Closing due to lack of activities.

**Closed by esjeon** 2020-05-31 17:47 UTC
