### ISSUE TITLE
[Feature Request] float all

### ISSUE THREAD

**Issue by zyf0330** [esjeon/krohnkite#43] opened 2019-06-21 04:29 UTC
I don't know how to float all with one action. It means all window be reset, not in any layout.

**Comment by esjeon** [comment] 2019-06-21 07:15
Krohnkite internally uses a "floating" layouts for ignored screens. In the floating layout, every window simply floats regardless of its floating state. Is this what you are suggesting?

If that's the case, I will be able to expose the layout through keybinding.

**Comment by zyf0330** [comment] 2019-06-21 07:20
Yes, you are right. That is what I want. 
I think there should be a layout in which every window has its original state.

**Comment by lunarfyre7** [comment] 2019-08-23 20:21
I would like a feature like this too. Maybe instead of floating all, being able to toggle floating, maybe adding it to the list of layouts. Sometimes I find tiling the most fitting way to work, but other times I just want to use the default floating behavior from kwin and just disable the entire plugin. Being able to completely toggle float all and tile with a keybind would be great.

**Comment by esjeon** [comment] 2019-10-27 14:28
I just implemented the both feature mentioned here:
 * "float all" shortcut, which floats all visible windows in the current context (desktop, activity, display). A caveat is that windows will float in-place, instead of restoring their previous floating position.
 * "Floating Layout", which can be enabled in config. Note that switching in and out of Floating layout won't break floating states of windows. The layout doesn't put windows in float mode like the hotkey above, but it merely tiles windows in free form.

**Comment by zyf0330** [comment] 2019-10-28 01:57
Thanks a lot!

**Comment by phrxmd** [comment] 2019-11-03 07:53
This is very nifty, thank you! But it's one of those cases where one feature leads right to the next feature request :D 
Concretely, it wold be really nice if there was a way to "unfloat" all of them again. If you have a few open windows and use `floatAll`, you have to visit every single window and toggle the floating status in order to get them all back into tiles again.

Either `floatAll` could be a toggle (per screen/activity/desktop probably?) - hit it once to float them all, hit it again to unfloat them - or there could be an equivalent `tileAll` with a separate keyboard shortcut..

**Comment by zyf0330** [comment] 2019-11-04 03:23
@esjeon Hello, after upgrade, I don't see shortcut for "Floadting Layout".
@phrxmd good idea!

**Comment by esjeon** [comment] 2019-12-27 06:54
I made it toggle based on the number of floating windows. Windows will be tiled if more than half are floating, and floated if less.

**Comment by esjeon** [comment] 2020-01-05 06:17
I'm closing this due to lack of activities, but please feel free to comment.

**Closed by esjeon** 2020-01-05 06:17 UTC

**Comment by zyf0330** [comment] 2020-04-09 03:07
Sorry, after test, I find this feature is not what I want.
My situation is, I have some windows in one screen, and just two or three of them need be in tile mode, other not be displayed or switched to.
Now to do this, I must switch to tile mode, then change to every window and press meta+esc to float it, finally keep two or three windows I want to keep tile mode.

**Comment by esjeon** [comment] 2020-04-12 02:50
I don't clearly understand your problem. Maybe the problem is w/ the behavior of "floating all" feature, where windows don't preserve their previous floating state?

**Comment by zyf0330** [comment] 2020-04-12 05:04
I need after floating all windows, they won't be switched to and displayed. Like they are all minimized. Then I can choose several of them to not be floating and work with them.
Maybe I can switch desktop to do this.
