### ISSUE TITLE
plasmashell won't start after installation/deinstallation of this script

### ISSUE THREAD

**Issue by rominf** [esjeon/krohnkite#18] opened 2018-12-23 22:46 UTC
**Symptom**
`plasmashell` won't start.

**How to Reproduce**
1. Install the script.
2. Do not like it.
3. Uninstall it.
4. Reboot.

**Expected behavior**
Everything should work

**Environment**
 - Distro: openSUSE Krypton
 - KWin version: 5.14.80
 - Krohnkite version: b5cc33e76482a20e0ffbaf25a6360916ef33a6b1
 - List of KWin scripts in use: -

**Comment by rominf** [comment] 2018-12-23 22:49
After I deleted `~/.config/plasma-org.kde.plasma.desktop-appletsrc` `plasmashell` has started.

**Comment by esjeon** [comment] 2018-12-24 03:39
Hmm, it's hard to think this is anyway related to Krohnkite. [This](https://unix.stackexchange.com/questions/209317/where-are-default-plasma-5-settings-stored) suggests that the file you mentioned is related only to plasmoids.

**Comment by esjeon** [comment] 2018-12-24 03:49
Just tested this on a VM. Nope, I cannot reproduce by simply removing the script. I'm closing this.

**Closed by esjeon** 2018-12-24 03:49 UTC
Labels: bug
