### ISSUE TITLE
Virtual desktop paging causes windows to be unresponsive

### ISSUE THREAD

**Issue by dylrich** [esjeon/krohnkite#12] opened 2018-12-08 18:40 UTC
Hi! Big fan of krohnkite so far - thanks for making something so easy to use available for everyone!

I think I am experiencing a bug with it: When I switch virtual workspaces with my pager and then switch back, windows become unresponsive to interaction. The only thing I have found that works 100% of the time is to float the window with meta + f and then toggle float off again and all is good.

Any advice on how to fix this? Appreciate the help!

**Comment by esjeon** [comment] 2018-12-08 21:38
I have experienced the same bug already, but I'm completely failing at reproducing it. The symptom goes away after a reboot, and will come only back after hours of usage.

A possible hack would be jiggle windows whenever the current desktop is changed.

**Comment by esjeon** [comment] 2018-12-09 10:19
Implemented the hacky hack that I mentioned above. Whenever desktops are switched, tile will jiggle by 1px to force window re-rendering. It's (hopefully) *almost* unnoticeable.

**Comment by esjeon** [comment] 2018-12-11 23:49
Hmm, I'm closing this since the fix has been working pretty good for me.

**Closed by esjeon** 2018-12-11 23:49 UTC
Labels: bug
