### ISSUE TITLE
Disconnecting external monitor(s) crashes KWin when there are windows present

### ISSUE THREAD

**Issue by hjri** [esjeon/krohnkite#35] opened 2019-03-22 14:51 UTC
**Symptom**
KWin crashes when disconnecting a monitor, plasma panel is sometimes displaced as a consequence.

**How to Reproduce**
1. Run krohnkite with multi-display setup.
2. Disconnect monitor
3. See "Sorry KWin crashed"

**Expected behavior**
No KWin crashes

**Environment**
 - Distro: Debian testing + unstable/experimental
 - KWin version: 5.14.5
 - Krohnkite version: 530ca22f1b3b435321283bff4e7deacacd256fde
 - List of KWin scripts in use: Krohnkite, "Enforces Window Decorations on GTK+ window"

**Notes**
Haven't tested on latest commit yet and no logs just yet. Crashes only when screen is removed, connecting another screen works fine. Only crashes when there are windows present on screen removed, windows on remaining screen seem to be moved relatively to old offsets (removed screen was above remaining, all windows on remaining screen are moved to the very bottom until you try resizing them)

**Comment by hjri** [comment] 2019-03-22 14:53
Just a note that KWin doesn't crash with Krohnkite disabled

**Comment by JustinTimperio** [comment] 2019-03-22 15:15
Hi @hjri, just wanted to corroborate this bug as I am getting identical behavior.

From what I can tell debugging it, the script still functions normally after the fault, but it causes a permanent kwin fault that displaces the wallpaper, widgets and other desktop elements in the direction of the now missing screen(s). Ghost monitor is probably the best word for it.

**Comment by esjeon** [comment] 2019-03-25 23:04
Hmm, I cannot reproduce this on VM, and don't have extra monitor that I can test this on. I'll try this on my old laptop, but it will take some time.

It's possible that Krohnkite is throwing an invalid screen number to KWin, and KWin doesn't validate the value and simply dies in the middle.

**Comment by hjri** [comment] 2019-04-01 09:35
Just tested it on latest commit c9e7611d52a00f0a9814dddc7a7838552be56f19, still the same.

Some logging right before crash/monitor disconnect:
```
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4850, resource id: 54570727, major code: 15 (QueryTree), minor code: 0
qml: [41.117] onWindowChanged: comment=screen=0 window=Window(KWin(5c00007.konsole))
qml: [41.117] arrange
qml: [41.118] arrangeScreen: ctx=KWinCtx(0, Default, 1) layout=TileLayout(nmaster=1, ratio=0.55) tiles=0 visibles=1
qml: [41.119] onWindowChanged: comment=screen=0 window=Window(KWin(5600007.ksysguard))
qml: [41.119] arrange
qml: [41.12] arrangeScreen: ctx=KWinCtx(0, Default, 1) layout=TileLayout(nmaster=1, ratio=0.55) tiles=0 visibles=1
qml: [41.121] onWindowChanged: comment=screen=0 window=Window(KWin(580002e.firefox))
qml: [41.121] arrange
qml: [41.121] arrangeScreen: ctx=KWinCtx(0, Default, 1) layout=TileLayout(nmaster=1, ratio=0.55) tiles=1 visibles=2
qml: [41.122] onWindowGeometryChanged: window=Window(KWin(580002e.firefox))
qml: [41.128] onWindowGeometryChanged: window=Window(KWin(580002e.firefox))
Application::crashHandler() called with signal 11; recent crashes: 1
KCrash: crashing... crashRecursionCounter = 2
```

**Comment by hjri** [comment] 2019-04-01 09:47
Found out that crash only happens when screens are arranged vertically. This screen arrangement also brings many other bugs in KDE https://bugs.kde.org/show_bug.cgi?id=404837

**Comment by esjeon** [comment] 2019-12-17 02:15
I'm closing this because upstream patched this, and is not reproducible even on physical dual screen setup.

**Closed by esjeon** 2019-12-17 02:15 UTC
Labels: bug
